image: coderus/sailfishos-platform-sdk-base:3.0.2.8

before_script:
 - source vince.env

stages:
 - build

run-build:
  stage: build
  script:
  - ./run-mic.sh 

  only:
   - web
   - tags

  artifacts:
    paths:
    - sfe-*/*.zip
