# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: RunsInContainer
  container: sfossdk
    image:coderus/sailfishos-platform-sdk-base:3.0.3.8
    options:/bin/bash
  steps:
  - script: source vince.env
  - script: ./run-mic.sh 
