name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
       image: docker://coderus/sailfishos-platform-sdk-base:3.1.0.12
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Build
      run: ./run-mic.sh
      
    - name : Upload packages
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt packages
        path: sfe-*/*.zip
